### ISSUE TITLE
Explain use case

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [rakyll/autopprof#2]
Hey, nice project!

I am new to the Golang profiling world.
I was unsure what was the difference between standard `pprof` and `autopprof`.
After trying your example I think I understand the advantages of your project:

> `autopprof` allows you to manually start the profiling at any arbitrary moment and for any specified duration.
> As opposed to `pprof` which starts at the beginning of the program and can only be stopped manually (i.e. SIGINT) or when the program ends.

Did I get that right?
Your tool is very useful for newcomers, I think adding an explanation of the advantages of `autopprof` in the README would be helpful.

**Comment by rakyll** [comment]
Closed via https://github.com/rakyll/autopprof/commit/31be2b066678643f362f953314a50f86f6d2b90f.
